const screens = {
  login: 'Login',
  register: 'Register',
  reset_pass: 'ResetPassword',
  home: 'Home',
  stack_app: 'AppStack',
  stack_auth: 'AuthStack',
  projects: 'Projects',
  profile: 'profile',
  app_screen: 'app_navigation',
  chats_screen: 'Chats',
  conversation: 'conversation',
  payments: 'Payments',
  logout: 'Logout',
  main_activity: 'MainActivity',
  location_picker: 'LocationPicker',
  rate_client: 'rateClient',
  project_info: 'projectInfo',
  fundi_reviews: 'FUNDIREVIEWS',
  profile_category_picker: 'profile_category_picker',
  profile_basic_info: `Profile_basic_info`,
  profile_reset_password: `profile_reset_password`,
};

export {screens};
